---
- name : ec2-webapp
  hosts: localhost
  connection: local
  tasks :

  - name : launch ec2 instance for Webapp
    ec2 :
      instance_type : t2.micro
      instance_tags:
        name: devops_dockerinstance
      key_name : devOps-key
      image : ami-0f884a43c583aa2fb
      region : us-east-2
      group : launch-wizard-1
      count : 1
      vpc_subnet_id : subnet-864480ed
      wait : yes
      assign_public_ip : yes
